[project]
name = "Slade_et_al_mapping_invasive_Neltuma_Kalahari"

[dependencies]
CAST = "*"
DT = "*"
DiceKriging = "*"
crew = "*"
dplyr = "*"
exactextractr = "*"
ggplot2 = "*"
gt = "*"
jsonlite = "*"
lightgbm = "*"
markdown = "*"
mlr3 = "*"
mlr3filters = "*"
mlr3learners = "*"
mlr3mbo = "*"
mlr3pipelines = "*"
mlr3spatiotempcv = "*"
mlr3tuning = "*"
mlr3tuningspaces = "*"
mlr3viz = "*"
patchwork = "*"
purrr = "*"
qs2 = "*"
quarto = "*"
ranger = "*"
readxl = "*"
rgenoud = "*"
sf = "*"
shiny = "*"
shinybusy = "*"
tarchetypes = "*"
targets = "*"
terra = "*"
tidyr = "*"
tidyterra = "*"
xgboost = "*"
yaml = "*"

[dependencies.mlr3extralearners]
git = "mlr-org/mlr3extralearners"
rev = "8f53c21292f2a986c77201f0e4cde1ee30466b80"
