#This script explores the diffeR package in R and the alternatives to using kappa for confusion matrix accuracy assessment
#Calculates confusion matrix metrics as per Pontius Jr., R.G., Millones, M. 2011. Death to Kappa: birth of quantity 
#disagreement and allocation disagreement for accuracy assessment. 
#International Journal of Remote Sensing 32 (15), 4407-4429.
#To be used with confusion matrix table generated by a classification algorithm

#install.packages("tidyverse")
#install.packages("diffeR")
#install.packages("dplR")
#install.packages("readtext")

library(diffeR)
library(readtext)

#Read in Data

Confusion1 <- read.csv("E:/Glenn/Botswana/RF/Python/Bokspits_1/Bokspits_1_RF_CHM_conf_matrix.csv")
Base_results <- read.csv("E:/Glenn/Botswana/RF/Python/Bokspits_1/Bokspits_1_RF_CHM_Summary.txt", header = FALSE)
#view (Base_results)
# Prepare data table for diffeR package 

Confusion4 <- subset(Confusion1, select = -c(row_0,All) )#removes unwanted columns from original Python output
Confusion3 <- Confusion4[-c(7),]#removes the last totals row
Confusion2 <- as.matrix(Confusion3) #converts table into matrix

dim (Confusion2) #checks dimensions of table
summary (Confusion2) #checks summary of table
head (Confusion2) #checks first few rows of table



diffTablej(Confusion2, digits = 2, analysis = "error")
#calculates quantity, exchange and shift components of difference, as well as the overall difference, at
#the category level from a contingency table derived from the crosstabulation between a comparison
#variable (or variable at time t), and a reference variable (or variable at time t+1).
#
categoryComponentsPlot (ctmatrix=Confusion2)
# stacked barplot showing for each category the quantity, exchange and shift
#components of difference between the comparison map/variable (or map/variable 
#at time t) and the reference map/variable (or map/variable at time t+1)
#
exchangeDij(Confusion2)
exchangeDj(Confusion2)
overallAllocD(Confusion2)
overallComponentsPlot(ctmatrix=Confusion2)
overallDiff(Confusion2)
overallDiffCatj(Confusion2)
overallExchangeD(Confusion2)
overallQtyD(Confusion2)
overallShiftD(Confusion2)
overallSourcesPlot(ctmatrix=Confusion2) 
quantityDj(Confusion2)
#sample2pop(ctmatrix, population)
#Cannot get sample2pop(ctmatrix, population) to work at the moment
shiftDj(Confusion2)
#calculates shift difference at the category level from a contingency table derived
#from the crosstabulation between a comparison variable (or variable at time t), 
#and a reference variable (or variable at time t+1). Shift refers to the difference 
#remaining after subtracting quantity difference and exchange from the overall difference.
#
categorySourcesPlot(ctmatrix=Confusion2)
# stacked barplot showing for each category the agreement and the omission and comission
#components of difference between the comparison map/variable (or map/variable at time t) 
#and the reference map/variable (or map/variable at time t+1)


