<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>refactor-3.0-plan</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="refactor-3.0-plan_files/libs/clipboard/clipboard.min.js"></script>
<script src="refactor-3.0-plan_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="refactor-3.0-plan_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="refactor-3.0-plan_files/libs/quarto-html/popper.min.js"></script>
<script src="refactor-3.0-plan_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="refactor-3.0-plan_files/libs/quarto-html/anchor.min.js"></script>
<link href="refactor-3.0-plan_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="refactor-3.0-plan_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="refactor-3.0-plan_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="refactor-3.0-plan_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="refactor-3.0-plan_files/libs/bootstrap/bootstrap-9fc26de039bfee7849f91cae3981fcd7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="refactor-3.0-from-reproduction-to-the-paper-we-want" class="level1">
<h1>refactor-3.0: from reproduction to the paper we want</h1>
<p>Branch <code>refactor-3.0</code>, cut from <code>refactor-v2.0</code> at <code>d067afe</code> (2026-09-16). Audience: Hugh and Andy. Decisions needed are marked <strong>[HUGH]</strong> / <strong>[ANDY]</strong> and collected in section 7. Findings referenced as 7.x live in <code>refactor-findings.md</code>.</p>
<section id="where-v2.0-leaves-us" class="level2">
<h2 class="anchored" data-anchor-id="where-v2.0-leaves-us">0. Where v2.0 leaves us</h2>
<p>The reproduction draft is complete: 1,624 targets rebuild the manuscript’s numbers, figures and tables from the raw inputs, in ~38 CPU-hours. What it established, in one line each:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Drone accuracy</td>
<td>~87% grand mean, “~90%” 2-3 points optimistic; learner choice is within noise; boundaries are linear (glmnet top) (7.28)</td>
</tr>
<tr class="even">
<td>WV2 accuracy</td>
<td>64% under 10x10 spatial CV; the reported 75.8% is reproduced to the decimal by <em>non-spatial</em> CV, and is a function of fold count (0.49 at 5 folds -&gt; 0.71 at 40) (7.34)</td>
</tr>
<tr class="odd">
<td>Cross-scale calibration</td>
<td>the +6.1% reverses: field points alone 66.8% &gt; drone-purity training 64.3% (7.37)</td>
</tr>
<tr class="even">
<td>Smoothing</td>
<td>the modal filter erases sparse Neltuma; at WV2 it halves recall for no precision; S10’s +24.8% is two filters roughly cancelling (7.31, 7.35)</td>
</tr>
<tr class="odd">
<td>Phases</td>
<td>Dominance reproduces; 40% of the landscape flips Pre-/Initial-Incursion with the surface choice (7.35)</td>
</tr>
<tr class="even">
<td>Grain</td>
<td>Neltuma precision against drone maps 0.40 -&gt; 0.24 -&gt; 0.15 (WV2 -&gt; Planet -&gt; S2); overall accuracy is not monotone (7.37)</td>
</tr>
<tr class="odd">
<td>Sub-pixel cover</td>
<td>1.1% / 0.9% / 0.3% of pixels reach the purity threshold per sensor (Fig 5)</td>
</tr>
</tbody>
</table>
<p>Compute profile of the store: landscape predictions 11 h and 16 GB (the per-class probability rasters), fits 7.5 h, tuning 4 h, everything else under 1 h each.</p>
</section>
<section id="what-is-actually-being-asked-of-the-rewrite" class="level2">
<h2 class="anchored" data-anchor-id="what-is-actually-being-asked-of-the-rewrite">1. What is actually being asked of the rewrite</h2>
<section id="the-original-plan-reviewer-response-document-to-pick-up-with-hugh" class="level3">
<h3 class="anchored" data-anchor-id="the-original-plan-reviewer-response-document-to-pick-up-with-hugh">1.1 The original plan (reviewer-response document, “To pick up with Hugh”)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Action</th>
<th>Status after v2.0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>targets across the workflow, provenance</td>
<td>done</td>
</tr>
<tr class="even">
<td>2</td>
<td>standardise class names, xlsx -&gt; json</td>
<td>done (classes.json)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>class probabilities as the foundation for conformal</td>
<td>done (<code>predict_type = "prob"</code> everywhere; prob rasters written)</td>
</tr>
<tr class="even">
<td>4</td>
<td>resolve the SPCV iteration discrepancy; audit blocking</td>
<td>done: 100 not 200; spcv_coords not block; fold-count sensitivity measured (7.34)</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Quarto manuscript + SI, Word output</td>
<td>HTML done; <strong>docx and SI pending</strong></td>
</tr>
<tr class="even">
<td>6</td>
<td>audit what “uncertainty” the outputs support</td>
<td>done: none, beyond CV variance (1.5)</td>
</tr>
<tr class="odd">
<td>7</td>
<td>check every reported statistic</td>
<td>done: sections 1-2 and 7.x</td>
</tr>
<tr class="even">
<td>8</td>
<td>capture the environment</td>
<td>done with uvr, not renv (9.x) <strong>[HUGH: renv.lock alongside?]</strong></td>
</tr>
<tr class="odd">
<td>9</td>
<td>README / workflow docs</td>
<td>partial; README still the original stub</td>
</tr>
<tr class="even">
<td>10</td>
<td>reproducibility checks against manuscript statistics</td>
<td>partial (validators on inputs; no statistic assertions)</td>
</tr>
<tr class="odd">
<td>11</td>
<td>probabilistic / conformal extension</td>
<td><strong>this refactor</strong></td>
</tr>
<tr class="even">
<td>12-14</td>
<td>reconcile manuscript, SI, responses</td>
<td>Andy, after this refactor</td>
</tr>
</tbody>
</table>
</section>
<section id="what-the-reviewers-need-to-see" class="level3">
<h3 class="anchored" data-anchor-id="what-the-reviewers-need-to-see">1.2 What the reviewers need to see</h3>
<p>Reviewer 1: show the spatial blocking (which areas held out, L239-242); an uncertainty layer (L253); ranges of km² and % invaded, not absolutes (L272); a defensible inference method for the settlement/road relationships, citing prediction-powered inference (L278); UA and PA for Table S9; a treatment table instead of “the multispectral + CHM + NDVI stack”; the nested design made visible (Fig 4).</p>
<p>Reviewer 2: satellite performance is overestimated and the 24.8% / 34.6% discrepancy insufficiently disclosed; it must propagate to the abstract, the conclusions and the area claims (“16 km² established, 356 km² expanding”); cites Angelopoulos &amp; Bates (2021) on conformal prediction directly.</p>
<p>Every one of these maps onto a pipeline product below.</p>
</section>
</section>
<section id="design-principles-for-3.0" class="level2">
<h2 class="anchored" data-anchor-id="design-principles-for-3.0">2. Design principles for 3.0</h2>
<ol type="1">
<li><strong>Honest spatial evaluation is the result, not the obstacle.</strong> Report the accuracy <em>curve</em> against holdout distance / fold geometry, and pick a primary design that matches the question (“a new area of this landscape”).</li>
<li><strong>Probabilities are the product; hard classes are a view of them.</strong> Every landscape output carries calibrated uncertainty, and every area statistic is an interval.</li>
<li><strong>One code path for every sensor.</strong> The drone is the finest sensor, not a special case: sites x sensors x training-source x learner, one graph.</li>
<li><strong>Raw surfaces only.</strong> The modal filter is retired as a processing step and reported once as a sensitivity analysis (it is a recall penalty, 7.35).</li>
<li><strong>Measured, not argued.</strong> Fold-count curves, coverage curves, calibration plots and timing tables are figures, not paragraphs.</li>
</ol>
</section>
<section id="the-probabilistic-and-conformal-design" class="level2">
<h2 class="anchored" data-anchor-id="the-probabilistic-and-conformal-design">3. The probabilistic and conformal design</h2>
<section id="what-conformal-prediction-gives-us-here" class="level3">
<h3 class="anchored" data-anchor-id="what-conformal-prediction-gives-us-here">3.1 What conformal prediction gives us here</h3>
<p>Split (inductive) conformal prediction turns any classifier’s probabilities into <strong>prediction sets</strong> with a finite-sample coverage guarantee: at level alpha = 0.1, the true class is in the set for &gt;= 90% of exchangeable test points. For a sparse target the interesting outputs are:</p>
<ul>
<li><strong>set size per pixel</strong> - the uncertainty layer R1 asked for; 1 = confident, 2+ = ambiguous, 0 = “none of the classes fit” (novel cover);</li>
<li><strong>“Neltuma cannot be ruled out”</strong> - the pixels whose set contains Neltuma, which is the management map: where to look, with a stated error rate;</li>
<li><strong>area bounds</strong> - lower bound = pixels whose set is exactly {Neltuma}, upper bound = pixels with Neltuma in the set. That is the “range of km² and %” R1 wants, with the reviewer-requested over-prediction folded in.</li>
</ul>
</section>
<section id="method-choices-hugh" class="level3">
<h3 class="anchored" data-anchor-id="method-choices-hugh">3.2 Method choices <strong>[HUGH]</strong></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Choice</th>
<th>Recommendation</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Score</td>
<td>LAC (1 - p_true) as primary, APS/RAPS reported</td>
<td>LAC gives the smallest sets at nominal coverage; APS gives better conditional coverage. Both are ten lines.</td>
</tr>
<tr class="even">
<td>Class-conditional</td>
<td><strong>Mondrian (per-class) calibration</strong></td>
<td>Marginal coverage can be met by covering the common classes and failing Neltuma; per-class thresholds guarantee Neltuma’s own coverage.</td>
</tr>
<tr class="odd">
<td>Calibration data</td>
<td>the out-of-fold probabilities we already produce (100 spatial-CV iterations per task) - cross-conformal / CV+ thresholds</td>
<td>Free: <code>run_resample</code> already stores them; spatially held-out by construction, so exchangeability is “a new spatial fold of this landscape”, which is the deployment claim.</td>
</tr>
<tr class="even">
<td>Levels</td>
<td>alpha in {0.05, 0.10, 0.20}; report coverage curves</td>
<td>The paper should show the trade-off, not one number.</td>
</tr>
<tr class="odd">
<td>Validation</td>
<td>empirical coverage per class and per site on spatial holdout; calibration reliability diagrams for p(Neltuma)</td>
<td>Coverage-by-site is the honest statement of spatial transfer.</td>
</tr>
<tr class="even">
<td>Implementation</td>
<td><code>R/conformal.R</code>, ours</td>
<td>Nothing installed does Mondrian split conformal for mlr3 classification; the maths is small and we want it auditable.</td>
</tr>
</tbody>
</table>
</section>
<section id="inference-on-the-maps-prediction-powered-inference-hugh" class="level3">
<h3 class="anchored" data-anchor-id="inference-on-the-maps-prediction-powered-inference-hugh">3.3 Inference on the maps: prediction-powered inference <strong>[HUGH]</strong></h3>
<p>R1’s L278 point is right: regressions on model output are inference on predictions. Prediction-powered inference (Angelopoulos et al.&nbsp;2023) is the fix and fits our data exactly: the drone-overlap pixels are a <em>labelled</em> set (drone class as label, satellite class as prediction), the whole scene is the <em>unlabelled</em> set. PPI gives a confidence interval for <strong>Neltuma area</strong> and for <strong>cover-by-distance-to-settlement</strong> that accounts for the satellite’s error rate measured on the drone overlap. It costs one function and answers R1 and R2 in the same object.</p>
</section>
<section id="spatial-cross-validation-knndm-decided-2026-09-16-hugh" class="level3">
<h3 class="anchored" data-anchor-id="spatial-cross-validation-knndm-decided-2026-09-16-hugh">3.4 Spatial cross-validation: kNNDM (decided 2026-09-16 [HUGH])</h3>
<p>Prediction-domain adaptive evaluation (Linnenbrink, Nowosad &amp; Meyer 2026, arXiv:2605.13689; kNNDM, Linnenbrink et al.&nbsp;2024, GMD 17:5897) replaces block CV. Folds are built so the nearest-neighbour-distance distribution between test and training points matches that between the <em>prediction domain</em> and the training points; the mismatch is a Wasserstein statistic W that we report. This is the honest evaluation for the question each map answers, and it resolves 7.34 by construction rather than by choosing a fold count.</p>
<ul>
<li>Implementation: <strong>CAST::knndm via mlr3spatiotempcv’s <code>repeated_spcv_knndm</code></strong> (already in our 2.3.5; CAST added to the environment). blockCV’s port was considered and not adopted: no mlr3 integration, a heavier GDAL-linked dependency tree, and comparing two implementations of one algorithm measures the port, not the method.</li>
<li>Prediction domains, per question: drone arm -&gt; the site’s own AOI (the map is that site); satellite arms -&gt; the 445 km2 study-area boundary. The two accuracies differ legitimately and are reported as such.</li>
<li>k: 10 for the drone arm; for the satellite arms k chosen by W (the paper recommends 4-6 for severely clustered samples), with W and the NND ECDF figure shown - that is R1’s “show the blocking”.</li>
<li>10 repeats over different prediction-point samples; tuning inner folds kNNDM too (5-fold), MBO 30, futures on (4.2).</li>
<li>Secondary figure: the fold-count / design curve (7.34) so the reader sees what the choice of evaluation does to the number.</li>
<li>Area of applicability (Meyer &amp; Pebesma 2021) computed alongside, and the conformal set-size layer reported over it.</li>
</ul>
</section>
<section id="learners-and-training-sources-hugh" class="level3">
<h3 class="anchored" data-anchor-id="learners-and-training-sources-hugh">3.5 Learners and training sources <strong>[HUGH]</strong></h3>
<ul>
<li>Learners: glmnet, lightgbm, ranger, svm (linear/radial), untuned ranger baseline. Drop xgboost (lightgbm covers it, 7.37 shows no gap) and decide on the stacked ensemble: it never won by a clear margin anywhere and costs 45 minutes a task. Keep it only if the paper wants to keep saying “ensemble”.</li>
<li>Training sources per satellite: <strong>field points</strong> (0.8 m buffers) and <strong>drone-purity from OUR raw surfaces</strong> - both reported; Glen’s archived extraction becomes a reproduction-only check. The cross-scale claim is then the honest comparison of the two.</li>
<li>The <code>dr_smooth</code> arms retire with the filter.</li>
</ul>
</section>
<section id="the-sensor-comparison" class="level3">
<h3 class="anchored" data-anchor-id="the-sensor-comparison">3.6 The sensor comparison</h3>
<p>Report per sensor: spatial-CV accuracy with intervals, pixel-level precision/recall against the drone maps (the grain story that actually holds), conformal set-size distributions, and Neltuma area as PPI intervals. Fig 7E becomes precision/recall + coverage, not “overall accuracy”.</p>
</section>
<section id="phases-with-uncertainty" class="level3">
<h3 class="anchored" data-anchor-id="phases-with-uncertainty">3.7 Phases with uncertainty</h3>
<p>Per hexagon: P(cover &gt; threshold) from the pixel probabilities (or the conformal bounds), giving a phase map with a confidence class (“Expansion, &gt;90% sure” vs “Expansion or Incursion”) and area ranges per phase. That is Table 1 with the intervals R1 asked for.</p>
</section>
<section id="sub-pixel-fractional-cover-unmixing---a-separate-product-not-a-by-product-hugh-andy" class="level3">
<h3 class="anchored" data-anchor-id="sub-pixel-fractional-cover-unmixing---a-separate-product-not-a-by-product-hugh-andy">3.8 Sub-pixel fractional cover (“unmixing”) - a separate product, not a by-product <strong>[HUGH]</strong> <strong>[ANDY]</strong></h3>
<p>Class probabilities and fractional cover are different quantities. The classifier’s p(Neltuma) is the calibrated probability that a pixel’s <em>dominant</em> cover is Neltuma, learned from pixels that were &gt;= 95% / 85% / 65% pure. It says nothing about a 10 m pixel that is 20% Neltuma - and Fig 5 shows that is almost every pixel with any Neltuma at all: only 1.1% / 0.9% / 0.3% of pixels reach the purity threshold, so the classification design discards &gt;99% of the cross-scale information at every sensor and then struggles at exactly the sparse end the paper is about (7.37: Neltuma recall 0.65 -&gt; 0.39 -&gt; 0.57).</p>
<p>The purity extraction already computes the answer for every satellite pixel over the drone sites: <code>frac_1</code> = Neltuma fraction from the raw drone surface, for 690k WV2, 179k Planet and 17k S2 pixels. That is a regression training set, and the same drone maps that were “cross-scale calibration” for a handful of pure pixels become labels for all of them.</p>
<p><strong>Design</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Choice</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Response</td>
<td>Neltuma fraction per satellite pixel (0-1); woody-vs-other fraction as a second target if the paper wants it</td>
<td>Compositional all-class unmixing (Dirichlet / multi-output) is a later option; Neltuma is the claim</td>
</tr>
<tr class="even">
<td>Labels</td>
<td>raw drone surfaces only (7.31); label noise from drone error (~10%) carried into PPI</td>
<td>the filtered surfaces would erase the sparse end of the target</td>
</tr>
<tr class="odd">
<td>Learners</td>
<td>regression twins of the classification set: glmnet, lightgbm, ranger, svm</td>
<td>same 9-band cubes; same kNNDM folds</td>
</tr>
<tr class="even">
<td>Zero inflation</td>
<td>evaluate direct regression against a hurdle (presence classifier x cover regression); trees may not need it, glmnet will</td>
<td>86% of WV2 pixels are zero</td>
</tr>
<tr class="odd">
<td>Evaluation</td>
<td>kNNDM folds; RMSE/MAE and calibration of cover, plus detection metrics at cover thresholds (&gt;0, &gt;0.1, &gt;0.5)</td>
<td>the sparse-detection question is a threshold on cover</td>
</tr>
<tr class="even">
<td>Uncertainty</td>
<td><strong>CV+ / jackknife+ intervals via mlr3pipelines <code>learner_pi_cvplus</code></strong> - the regression conformal tool already in our stack and the one Hugh has used</td>
<td>coverage checked per site as for the sets</td>
</tr>
<tr class="odd">
<td>Baseline</td>
<td>linear spectral unmixing with endmembers from pure pixels</td>
<td>the classical method reviewers will expect to see beaten</td>
</tr>
<tr class="even">
<td>Products</td>
<td>Neltuma fractional-cover raster + lower/upper interval rasters per sensor; area = sum of fractions x pixel area with PPI intervals; phases per hexagon from mean cover directly</td>
<td>no majority vote, no purity threshold anywhere in the chain</td>
</tr>
</tbody>
</table>
<p><strong>What it changes in the paper.</strong> The satellite arms’ primary Neltuma product becomes fractional cover with intervals; the multi-class classification stays for the vegetation-class maps (Fig 6/7) and the conformal sets. Table 1 / Fig 8 derive from cover, not from thresholded classes, so the 40-point Pre-/Initial-Incursion flip (7.35) disappears by construction. The sensor-grain story becomes “how well can each grain resolve cover” - a cleaner claim than accuracy of a dominant class.</p>
<p><strong>Phase.</strong> C2, in parallel with the conformal-set work: the extraction is done, the folds are shared, the learners are the regression twins, and the interval machinery is off the shelf.</p>
<p><strong>Decisions.</strong> D11 Neltuma-only fraction vs compositional all-class unmixing (recommend Neltuma-only first) [ANDY]; D12 hurdle vs direct regression, decided by measurement [HUGH]; D13 include the endmember baseline (recommend yes, it costs a day) [HUGH].</p>
</section>
</section>
<section id="workflow-improvements-the-engineering-half" class="level2">
<h2 class="anchored" data-anchor-id="workflow-improvements-the-engineering-half">4. Workflow improvements (the engineering half)</h2>
<section id="graph-shape" class="level3">
<h3 class="anchored" data-anchor-id="graph-shape">4.1 Graph shape</h3>
<ul>
<li>One <code>tar_map</code> over <code>sensor x site x source x learner</code> with the drone as a sensor; shared training-table, cube, fit, predict and compare code. Removes the three near-duplicate WV2 / sat / drone blocks in <code>_targets.R</code>.</li>
<li><code>pred_*</code> depend on the <strong>winner’s</strong> configuration, not the list of all tuned configs (a one-learner change re-predicted seven sites, 7.37).</li>
<li>Split <code>resampling.yml</code> into <code>evaluation.yml</code> (folds, budget, learners) and <code>prediction.yml</code> so an evaluation edit cannot invalidate predictions.</li>
</ul>
</section>
<section id="compute" class="level3">
<h3 class="anchored" data-anchor-id="compute">4.2 Compute</h3>
<ul>
<li><code>tune_config()</code> gets a future plan (<code>multisession</code>, never <code>multicore</code> after lightgbm - 7.35); measured 4.4x at 8 workers.</li>
<li>Predictions tiled with <code>terra</code> windows and <code>cores</code>; probability rasters written as <strong>INT16 scaled</strong> COGs (16 GB -&gt; ~4 GB) and the class raster derived from them, not stored twice.</li>
<li>Conformal outputs are thresholding passes over the prob rasters: cheap.</li>
</ul>
</section>
<section id="data-and-formats" class="level3">
<h3 class="anchored" data-anchor-id="data-and-formats">4.3 Data and formats</h3>
<ul>
<li>Vectors: <code>.fgb</code> everywhere. One conversion pass over the mirrored shapefiles with provenance (<code>tools/convert-vectors.sh</code>), manifest updated, and the CRS-less layers (WV2_clip, All_points_buffered_additional) fixed at conversion. (Decision 5.4, deferred from v2.0.)</li>
<li>Tables: CSV/JSON in <code>inst/</code>, <code>qs</code> in the store, Parquet for anything shared out.</li>
<li>Inputs manifest becomes the only place a path is spelled.</li>
</ul>
</section>
<section id="tests-and-checks" class="level3">
<h3 class="anchored" data-anchor-id="tests-and-checks">4.4 Tests and checks</h3>
<ul>
<li><code>testthat</code> for the pure functions: <code>balance_classes</code>, <code>vi_formulas</code> against the shipped rasters, phase thresholds, conformal coverage on synthetic data, PPI on a known population.</li>
<li>A <code>checks</code> target family asserting invariants after every run: class balance, CRS, band counts, coverage &gt;= 1 - alpha on holdout, and the handful of headline statistics the paper quotes (original plan item 10).</li>
<li>The fast profile stays the gate: nothing full-budget runs before it is green.</li>
</ul>
</section>
<section id="the-paper" class="level3">
<h3 class="anchored" data-anchor-id="the-paper">4.5 The paper</h3>
<ul>
<li><code>paper/manuscript.qmd</code> stops being verbatim: it becomes <em>the</em> manuscript, with the treatment table R1 asked for, every number an inline value, <code>docx</code> and HTML outputs, and <code>paper/supplement.qmd</code> for the SI.</li>
<li>Responses to reviewers as a third qmd reading the same values.</li>
<li>The colour-coded reproduction draft is kept as a record on <code>refactor-v2.0</code>, not carried forward.</li>
</ul>
</section>
<section id="repository" class="level3">
<h3 class="anchored" data-anchor-id="repository">4.6 Repository</h3>
<ul>
<li>README rewritten: what it is, how to run it (fast / full), where outputs land, the decision log.</li>
<li><code>docs/decisions.md</code>: the [HUGH]/[ANDY] decisions from the findings, as short ADRs, so the reasoning survives the findings file being retired.</li>
<li>Environment: uvr stays; export a <code>renv.lock</code>-equivalent for reviewers. <strong>[HUGH]</strong></li>
</ul>
</section>
</section>
<section id="sequence" class="level2">
<h2 class="anchored" data-anchor-id="sequence">5. Sequence</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Content</th>
<th>Gate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A. Foundations (1 wk)</td>
<td>4.1-4.4: unified graph, winner-only deps, tuning futures, INT16 probs, fgb conversion, tests. No science changes.</td>
<td>full run reproduces v2.0 numbers; wall time down</td>
</tr>
<tr class="even">
<td>B. Evaluation (1-2 wk)</td>
<td>3.4: variogram range, spcv_block primary, fold-count and LOSO figures, learner trim</td>
<td>fold/CV figures rendered; per-site holdout table</td>
</tr>
<tr class="odd">
<td>C. Uncertainty (2 wk)</td>
<td>3.1-3.3, 3.7: conformal calibration from resample predictions, set-size / Neltuma-possible / area-bound rasters, coverage validation, PPI areas, probabilistic phases</td>
<td>coverage &gt;= nominal on holdout per class; area intervals in Table 1</td>
</tr>
<tr class="even">
<td>C2. Fractional cover (1-2 wk, parallel)</td>
<td>3.8: cover regression on all purity-extraction pixels, CV+ intervals, endmember baseline, cover-derived areas and phases</td>
<td>interval coverage &gt;= nominal per site; cover RMSE per sensor</td>
</tr>
<tr class="odd">
<td>D. Sensors (1 wk)</td>
<td>3.5-3.6: field vs purity sources, precision/recall + coverage per sensor, Fig 7 redesign</td>
<td>sensor table with intervals</td>
</tr>
<tr class="even">
<td>E. Paper (1-2 wk)</td>
<td>4.5: manuscript, SI, responses; docx</td>
<td>Andy’s pass</td>
</tr>
</tbody>
</table>
<p>Phases A and B can run while C is designed; C is the critical path.</p>
</section>
<section id="risks" class="level2">
<h2 class="anchored" data-anchor-id="risks">6. Risks</h2>
<ul>
<li><strong>Exchangeability under spatial shift.</strong> Calibrating on spatial folds buys coverage for “another fold of this landscape”; a genuinely different region can still break it. Per-site coverage is reported, not assumed.</li>
<li><strong>Set sizes at coarse grain.</strong> Sentinel-2 at alpha = 0.1 may produce mostly 2-3 class sets; that is the honest result and Fig 7 should show it.</li>
<li><strong>Class scarcity.</strong> Mondrian thresholds for S.mellifera / Boscia rest on few calibration points; report n per class alongside coverage.</li>
<li><strong>Scope creep in the paper.</strong> The rewrite should change what the paper <em>claims</em>, not what it is about.</li>
</ul>
</section>
<section id="decisions-needed" class="level2">
<h2 class="anchored" data-anchor-id="decisions-needed">7. Decisions needed</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Decision</th>
<th>Recommendation</th>
<th>Owner</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>D1</td>
<td>Conformal score and Mondrian calibration</td>
<td>LAC + per-class, APS reported</td>
<td>HUGH</td>
</tr>
<tr class="even">
<td>D2</td>
<td>Primary CV design</td>
<td><strong>decided: kNNDM via CAST</strong>, domains per question</td>
<td>done</td>
</tr>
<tr class="odd">
<td>D3</td>
<td>Learner set; keep the stacked ensemble?</td>
<td>4 tuned + baseline; drop ensemble unless the text needs it</td>
<td>HUGH + ANDY</td>
</tr>
<tr class="even">
<td>D4</td>
<td>Training sources reported per satellite</td>
<td>field points + our-surface purity; archived as check</td>
<td>ANDY</td>
</tr>
<tr class="odd">
<td>D5</td>
<td>Retire the modal filter; smoothing as sensitivity only</td>
<td>yes</td>
<td>ANDY</td>
</tr>
<tr class="even">
<td>D6</td>
<td>PPI for areas and settlement gradients</td>
<td>yes</td>
<td>HUGH + ANDY</td>
</tr>
<tr class="odd">
<td>D7</td>
<td>Phase map as probabilistic membership with area ranges</td>
<td>yes</td>
<td>ANDY</td>
</tr>
<tr class="even">
<td>D8</td>
<td>Paper outputs: docx + HTML, SI as qmd</td>
<td>yes</td>
<td>ANDY</td>
</tr>
<tr class="odd">
<td>D9</td>
<td>Environment export for reviewers (renv.lock from uvr)</td>
<td>export, keep uvr</td>
<td>HUGH</td>
</tr>
<tr class="even">
<td>D10</td>
<td>Landsat arm in scope? (6.3)</td>
<td>out</td>
<td>ANDY</td>
</tr>
<tr class="odd">
<td>D11</td>
<td>Fractional cover: Neltuma-only vs compositional</td>
<td>Neltuma-only first</td>
<td>ANDY</td>
</tr>
<tr class="even">
<td>D12</td>
<td>Hurdle vs direct cover regression</td>
<td>measure both, pick by kNNDM RMSE + threshold detection</td>
<td>HUGH</td>
</tr>
<tr class="odd">
<td>D13</td>
<td>Endmember linear-unmixing baseline</td>
<td>yes</td>
<td>HUGH</td>
</tr>
</tbody>
</table>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>